name-template: $RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
pull-request:
  title-templates:
    fix: '🐛 $TITLE (#$NUMBER)'
    feat: '🚀 $TITLE (#$NUMBER)'
    default: '$TITLE (#$NUMBER)'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - "type: enhancement"
      - "type: new feature"
      - "type: major"
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - "type: improvement"
      - "type: bug"
      - "type: minor"
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'style'
      - 'test'
      - 'ci'
      - 'perf'
      - 'build'
      - 'deps'
      - "type: dependency upgrade"
      - "dependencies"
      - "type: ci"
      - "type: build"
  - title: '⏪ Reverts'
    labels:
      - 'revert'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'type: major'
  minor:
    labels:
      - 'type: minor'
  patch:
    labels:
      - 'type: patch'
  default: patch
template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
