http://stateless.co/hal_specification.html[HAL] is a standard format for representing JSON that has gained traction for its ability to represent links between resources and provide navigable APIs.

The JSON views plugin for Grails provides HAL support out-of-the-box. All JSON views implement the link:api/grails/plugin/json/view/api/HalView.html[HalView] trait, which provides an API for writing HAL views.

For example:

[source,groovy]
model {
    Book book
}
json {
    hal.links(book)
    hal.embedded {
        author( book.authors.first() ) { Author author ->
            name author.name
        }
    }
    title book.title
}

NOTE: The call to `hal.links()` has to be the first element within the `json{}` closure.

This produces the HAL output:

[source,javascript]
{
    "_links": {
        "self": {
            "href": "http://localhost:8080/book/show/1",
            "hreflang": "en",
            "type": "application/hal+json"
        }
    },
    "_embedded": {
        "author": {
            "_links": {
                "self": {
                    "href": "http://localhost:8080/author/show/1",
                    "hreflang": "en",
                    "type": "application/hal+json"
                }
            },
            "name": "Stephen King"
        }
    },
    "title": "The Stand"
}

==== Generating HAL Links

The above example uses the `hal.links(..)` method to render links for a domain resource and the `hal.embedded(..)` method to define any embedded objects that form part of the HAL response.

The `hal.links(..)` method will by default create a link to the resource, but you can define additional links by annotating the domain class with either `grails.rest.Linkable` or `grails.rest.Resource` and using the `link` method on the object:

[source,groovy]
book.link(rel:"publisher", href:"http://foo.com/books")


The link will then be included in the HAL output. 

If you prefer to define the HAL links yourself then you can do so by passing a closure to the `hal.links` method:

[source,groovy]
model {
    Book book
}
json {
    hal.links {
        self {
            href '...'
            hreflang 'en'
            type "application/hal+json"
        }
    }
    ...
}


==== Rendering Domain Classes as HAL

If you prefer to let the plugin handle the rendering of your object you can use the `hal.render(..)` method:

[source,groovy]
model {
    Book book
}
json hal.render(book)
    
The `hal.render` method works the same as the `g.render` method, accepting the same argument, the difference being it will output HAL links for the object via `hal.links`.    

==== Specifying the HAL Content Type

The default HAL response content type is `application/hal+json`, however as discussed in the section on <<json/contentNegotiation.adoc#mimeTypes,Custom Mime Type>> you can define your own response content types to represent your resources. 

For example given the following configuration in `grails-app/conf/application.yml`:

[source,groovy]
grails:
    mime:
        types:
            all:      "*/*"
            book:     "application/vnd.books.org.book+json"

You can set the HAL content type to an explicit content type or one of the named content types defined in `grails.mime.types` in `application.yml`:

[source,groovy]
model {
    Book book
}
hal.type("book")
json {
    ...
}

==== HAL Pagination

The JSON views plugin for Grails provides navigable pagination support.
Like the GSP `<g:paginate>` tag, the parameters include: `total`, `max`, `offset`, `sort` and `order`.

For example:

[source,groovy]
model {
    Iterable<Book> bookList
    Integer bookCount
    Integer max // optional, defaults to 10
    Integer offset // optional, defaults to 0
    String sort // optional
    String order // optional
}
json {
    hal.paginate(Book, bookCount, max, offset, sort, order)
    ...
}

NOTE: Similar to `hal.links()` the `hal.paginate()` has to be the first element within the `json{}` closure.

When accessing `http://localhost:8080/book?offset=10` this produces the navigable output like:

[source,javascript]
{
  "_links": {
    "self": {
      "href": "http://localhost:8080/book/index?offset=10&max=10",
      "hreflang": "en_US",
      "type": "application/hal+json"
    },
    "first": {
      "href": "http://localhost:8080/book/index?offset=0&max=10",
      "hreflang": "en_US"
    },
    "prev": {
      "href": "http://localhost:8080/book/index?offset=0&max=10",
      "hreflang": "en_US"
    },
    "next": {
      "href": "http://localhost:8080/book/index?offset=20&max=10",
      "hreflang": "en_US"
    },
    "last": {
      "href": "http://localhost:8080/book/index?offset=40&max=10",
      "hreflang": "en_US"
    }
  },
  ...
}

NOTE: If there aren't enough results to paginate the navigation links will not appear.
Likewise the `prev` and `next` links are only present when there is a previous or next page.