= Version History

The current release is {version}. Below is a version history.

For later releases check the release notes at: https://github.com/grails/grails-views/releases

*2.0.2*

* Fix bug where incorrect JSON was generated when all values are null in the nested object.

*2.0.1*

* Optimized `compileGsonViews` performance and reduced IOPS as well by compiling in parallel threads.
* Remove duplicate GSON classes from WAR.

*2.0.0*

* Grails 4, Gradle 5.
* Support for render embedded types with "includes".
* Fixed StackOverflow when rendering bidirectional associations.
* Allow augmenting model in JSON view.
* Fixed bugs related to exclude version and error properties from a Map model.

*1.3.0*

* The `includes` support has changed in a way that may break existing use cases. Having `includes: ['captain', 'captain.name']]` previously excluded all other fields except for `captain.name`. The `captain` in the list was necessary for `captain.name` to function as expected. Now the `captain` entry will cause all fields in `captain` to be rendered. To restore the previous behavior, simply remove the `captain` entry.  `includes: ['captain', 'captain.name']` -> `includes: ['captain.name]`.

*1.2.0*

* JSON API support
* Ability to register custom converters
* New configuration options for date formatting and unicode escaping
* New testing trait that integrates with the testing-support framework (1.2.5)

*1.1.0*

* Global template support
* Template inheritance
* Global templates for GORM for MongoDB / GeoJSON
* Support for easily testing JSON views with `JsonViewTest`
* Pagination support in HAL
* Better Embedded support in HAL
* Ability to access HTTP parameters and headers
* Resource expansion with the `expand` parameter
* Controller namespace support
* Support for a default `/object/_object.gson` template

*1.0.0*

* Initial 1.0.0 GA Release
