http://http://jsonapi.org/[JSON API] is a standard format for representing JSON.

The JSON views plugin for Grails provides JSON API support out-of-the-box. All JSON views implement the link:api/grails/plugin/json/view/api/JsonApiViewHelper.html[JsonApiViewHelper] trait, which provides an API for writing JSON API views.

Grails views makes a best effort to conform to the JSON API standard, however that only applies to the format of the data. The specification makes many assertions about response codes, url conventions, and other server related concepts that are overreaching.

The JSON API support in Grails also only applies to domain classes. Because the specification relies on concepts of relationships and identifiers, there is no clear way to determine how those concepts would apply to conventional Groovy classes. As a result, normal Groovy classes are not supported.

The simplest example of using JSON API simply passes a domain class to the `render` method of the `jsonapi` object.

For example:

[source,groovy]
model {
    Book book
}
json jsonapi.render(book)


In the example where `Book` looks like the following:

[source,groovy]
class Book {
    String title
    Author author
}

This is what an example `Book` instance rendered with JSON API might look like.

[source,json]
{
  "data": {
    "type": "book",
    "id": "3",
    "attributes": {
      "title": "The Return of the King"
    },
    "relationships": {
      "author": {
        "data": {
          "type": "author",
          "id": "9"
        }
      }
    }
  },
  "links": {
    "self": "http://localhost:8080/book/3",
    "related": {
      "href": "http://localhost:8080/author/9"
    }
  }
}


==== JSON API Object

To include the link:http://jsonapi.org/format/#document-jsonapi-object[JSON API Object] in the response, include a `jsonApiObject` argument to the `render` method.

[source,groovy]
model {
    Book book
}
json jsonapi.render(book, [jsonApiObject: true])

The response will contain `"jsonapi":{"version":"1.0"}` as the first key in the resulting object.

==== Meta Object

To add link:http://jsonapi.org/format/#document-meta[metadata] to your response, the `meta` argument can be passed to render with the value being the object that should be rendered. If this functionality is used in addition to `jsonApiObject: true`, the metadata will be rendered as the "meta" property of the "jsonapi" object.

[source,groovy]
model {
    Book book
}
json jsonapi.render(book, [meta: [name: "Metadata Information"]])

The response will contain `"meta":{"name":"Metadata Information"}` as the first key in the resulting object.

==== Rendering Errors

The JSON API specification has link:http://jsonapi.org/format/#errors[instructions on how to render errors]. In the case of the Grails implementation, this applies to both exceptions and validation errors.

===== Exceptions

If an exception is passed to the `render` method, it will be rendered within the specification.

In the example of an exception `new RuntimeException("oops!")`, the following will be rendered:

[source,json]
{
  "errors": [
    {
      "status": 500,
      "title": "java.lang.RuntimeException",
      "detail": "oops!",
      "source": {
        "stacktrace": [
          //An array of information relating to the stacktrace
        ]
      }
    }
  ]
}

===== Validation Errors

In the case of validation errors, the response will look like the following when a `name` property fails the blank constraint:

[source,json]
{
  "errors": [
    {
      "code": "blank",
      "detail": "Property [name] of class [class com.foo.Bar] cannot be blank",
      "source": {
        "object": "com.foo.Bar",
        "field": "name",
        "rejectedValue": "",
        "bindingError": false
      }
    }
  ]
}

==== Links

==== Pagination

==== Associations

==== Expand